import pandas as pd

STATES = ['alaska','alabama','arizona','arkansas','california','colorado',
'connecticut','delaware','florida','georgia','hawaii','idaho','illinois','indiana',
'iowa','kansas','kentucky','louisiana','maine','maryland','massachusetts',
'michigan','minnesota','mississippi','missouri','montana','nebraska',
'nevada','new hampshire','new jersey','new mexico','new york',
'north carolina','north dakota','ohio','oklahoma','oregon','pennsylvania',
'rhode island','south carolina','south dakota','tennessee','texas','utah',
'vermont','virginia','washington','washington d.c.','west virginia','wisconsin','wyoming']

COUNTRY_CODES = {
    'afghanistan':                                   'AF',
    'aland islands':                                 'AX',
    'albania':                                       'AL',
    'algeria':                                       'DZ',
    'american samoa':                                'AS',
    'andorra':                                       'AD',
    'angola':                                        'AO',
    'anguilla':                                      'AI',
    'antarctica':                                    'AQ',
    'antigua and barbuda':                           'AG',
    'argentina':                                     'AR',
    'armenia':                                       'AM',
    'aruba':                                         'AW',
    'australia':                                     'AU',
    'austria':                                       'AT',
    'azerbaijan':                                    'AZ',
    'bahamas':                                       'BS',
    'bahrain':                                       'BH',
    'bangladesh':                                    'BD',
    'barbados':                                      'BB',
    'belarus':                                       'BY',
    'belgium':                                       'BE',
    'belize':                                        'BZ',
    'benin':                                         'BJ',
    'bermuda':                                       'BM',
    'bhutan':                                        'BT',
    'bolivia':                                       'BO',
    'bosnia and herzegovina':                        'BA',
    'botswana':                                      'BW',
    'bouvet island':                                 'BV',
    'brazil':                                        'BR',
    'british indian ocean territory':                'IO',
    'brunei darussalam':                             'BN',
    'bulgaria':                                      'BG',
    'burkina faso':                                  'BF',
    'burundi':                                       'BI',
    'cambodia':                                      'KH',
    'cameroon':                                      'CM',
    'canada':                                        'CA',
    'cape verde':                                    'CV',
    'cayman islands':                                'KY',
    'central african republic':                      'CF',
    'chad':                                          'TD',
    'chile':                                         'CL',
    'china':                                         'CN',
    'christmas island':                              'CX',
    'cocos (keeling) islands':                       'CC',
    'colombia':                                      'CO',
    'comoros':                                       'KM',
    'congo':                                         'CG',
    'cook islands':                                  'CK',
    'costa rica':                                    'CR',
    "cote d'ivoire":                                 'CI',
    'croatia':                                       'HR',
    'cuba':                                          'CU',
    'cyprus':                                        'CY',
    'czech republic':                                'CZ',
    'denmark':                                       'DK',
    'djibouti':                                      'DJ',
    'dominica':                                      'DM',
    'dominican republic':                            'DO',
    'ecuador':                                       'EC',
    'egypt':                                         'EG',
    'el salvador':                                   'SV',
    'equatorial guinea':                             'GQ',
    'eritrea':                                       'ER',
    'estonia':                                       'EE',
    'ethiopia':                                      'ET',
    'falkland islands (malvinas)':                   'FK',
    'faroe islands':                                 'FO',
    'fiji':                                          'FJ',
    'finland':                                       'FI',
    'france':                                        'FR',
    'french guiana':                                 'GF',
    'french polynesia':                              'PF',
    'french southern territories':                   'TF',
    'gabon':                                         'GA',
    'gambia':                                        'GM',
    'germany':                                       'DE',
    'ghana':                                         'GH',
    'gibraltar':                                     'GI',
    'greece':                                        'GR',
    'greenland':                                     'GL',
    'grenada':                                       'GD',
    'guadeloupe':                                    'GP',
    'guam':                                          'GU',
    'guatemala':                                     'GT',
    'guernsey':                                      'GG',
    'guinea':                                        'GN',
    'guinea-bissau':                                 'GW',
    'guyana':                                        'GY',
    'haiti':                                         'HT',
    'heard island and mcdonald islands':             'HM',
    'holy see (vatican city state)':                 'VA',
    'honduras':                                      'HN',
    'hong kong':                                     'HK',
    'hungary':                                       'HU',
    'iceland':                                       'IS',
    'india':                                         'IN',
    'indonesia':                                     'ID',
    'iran':                                          'IR',
    'iraq':                                          'IQ',
    'ireland':                                       'IE',
    'isle of man':                                   'IM',
    'israel':                                        'IL',
    'italy':                                         'IT',
    'jamaica':                                       'JM',
    'japan':                                         'JP',
    'jersey':                                        'JE',
    'jordan':                                        'JO',
    'kazakhstan':                                    'KZ',
    'kenya':                                         'KE',
    'kiribati':                                      'KI',
    'korea':                                         'KR',
    'kuwait':                                        'KW',
    'kyrgyzstan':                                    'KG',
    "lao people's democratic republic":              'LA',
    'latvia':                                        'LV',
    'lebanon':                                       'LB',
    'lesotho':                                       'LS',
    'liberia':                                       'LR',
    'libyan arab jamahiriya':                        'LY',
    'liechtenstein':                                 'LI',
    'lithuania':                                     'LT',
    'luxembourg':                                    'LU',
    'macao':                                         'MO',
    'macedonia':                                     'MK',
    'madagascar':                                    'MG',
    'malawi':                                        'MW',
    'malaysia':                                      'MY',
    'maldives':                                      'MV',
    'mali':                                          'ML',
    'malta':                                         'MT',
    'marshall islands':                              'MH',
    'martinique':                                    'MQ',
    'mauritania':                                    'MR',
    'mauritius':                                     'MU',
    'mayotte':                                       'YT',
    'mexico':                                        'MX',
    'micronesia':                                    'FM',
    'moldova':                                       'MD',
    'monaco':                                        'MC',
    'mongolia':                                      'MN',
    'montenegro':                                    'ME',
    'montserrat':                                    'MS',
    'morocco':                                       'MA',
    'mozambique':                                    'MZ',
    'myanmar':                                       'MM',
    'namibia':                                       'NA',
    'nauru':                                         'NR',
    'nepal':                                         'NP',
    'netherlands':                                   'NL',
    'netherlands antilles':                          'AN',
    'new caledonia':                                 'NC',
    'new zealand':                                   'NZ',
    'nicaragua':                                     'NI',
    'niger':                                         'NE',
    'nigeria':                                       'NG',
    'niue':                                          'NU',
    'norfolk island':                                'NF',
    'northern mariana islands':                      'MP',
    'norway':                                        'NO',
    'oman':                                          'OM',
    'pakistan':                                      'PK',
    'palau':                                         'PW',
    'palestinian territory occupied':                'PS',
    'panama':                                        'PA',
    'papua new guinea':                              'PG',
    'paraguay':                                      'PY',
    'peru':                                          'PE',
    'philippines':                                   'PH',
    'pitcairn':                                      'PN',
    'poland':                                        'PL',
    'portugal':                                      'PT',
    'puerto rico':                                   'PR',
    'qatar':                                         'QA',
    'reunion':                                       'RE',
    'romania':                                       'RO',
    'russian federation':                            'RU',
    'rwanda':                                        'RW',
    'saint barthelemy':                              'BL',
    'saint helena ascension and tristan da cunha':   'SH',
    'saint kitts and nevis':                         'KN',
    'saint lucia':                                   'LC',
    'saint martin':                                  'MF',
    'saint pierre and miquelon':                     'PM',
    'saint vincent and the grenadines':              'VC',
    'samoa':                                         'WS',
    'san marino':                                    'SM',
    'sao tome and principe':                         'ST',
    'saudi arabia':                                  'SA',
    'senegal':                                       'SN',
    'serbia':                                        'RS',
    'seychelles':                                    'SC',
    'sierra leone':                                  'SL',
    'singapore':                                     'SG',
    'slovakia':                                      'SK',
    'slovenia':                                      'SI',
    'solomon islands':                               'SB',
    'somalia':                                       'SO',
    'south africa':                                  'ZA',
    'south georgia and the south sandwich islands':  'GS',
    'spain':                                         'ES',
    'sri lanka':                                     'LK',
    'sudan':                                         'SD',
    'suriname':                                      'SR',
    'svalbard and jan mayen':                        'SJ',
    'swaziland':                                     'SZ',
    'sweden':                                        'SE',
    'switzerland':                                   'CH',
    'syrian arab republic':                          'SY',
    'taiwan':                                        'TW',
    'tajikistan':                                    'TJ',
    'tanzania':                                      'TZ',
    'thailand':                                      'TH',
    'timor-leste':                                   'TL',
    'togo':                                          'TG',
    'tokelau':                                       'TK',
    'tonga':                                         'TO',
    'trinidad and tobago':                           'TT',
    'tunisia':                                       'TN',
    'turkey':                                        'TR',
    'turkmenistan':                                  'TM',
    'turks and caicos islands':                      'TC',
    'tuvalu':                                        'TV',
    'uganda':                                        'UG',
    'ukraine':                                       'UA',
    'united arab emirates':                          'AE',
    'united kingdom':                                'GB',
    'united states':                                 'US',
    'united states minor outlying islands':          'UM',
    'uruguay':                                       'UY',
    'uzbekistan':                                    'UZ',
    'vanuatu':                                       'VU',
    'venezuela':                                     'VE',
    'vietnam':                                       'VN',
    'virgin islands, british':                       'VG',
    'virgin islands, u.s.':                          'VI',
    'wallis and futuna':                             'WF',
    'western saharah':                               'EH',
    'yemen':                                         'YE',
    'zambia':                                        'ZM',
    'zimbabwe':                                      'ZW'
}

def file_to_list(f):
    with open(f) as l:
        return l.read().splitlines()

def print_full(x):
    pd.set_option('display.max_rows', len(x))
    print(x)
    pd.reset_option('display.max_rows')

def city_state_split(city_state):
    """ Splits a city and a state if separated by a comma. If no comma is
    found, city_state_split returns an empty city and the original value
    as the state. The method also attempts to determine the country based on
    either the state value or if the second value in the input is a country.

    Arguments
    ---------
    city_state : str
        A string containing the city and the state

    Returns
    python typle
        Three strings: city, state, country
    """
    csp = city_state.split(',')
    city = ''
    state = ''
    country = 'US'
    if len(csp) > 1:
        city = csp[0].strip()
        state = csp[1].strip()
        try:
            e = state.index('|')
        except:
            e = None
        state = state[:e]
    else:
        state = city_state.strip()
    if state.lower() in STATES:
        country = 'US'
    elif state.lower() in COUNTRY_CODES:
        country = COUNTRY_CODES[state.lower()]
        state = ''
    return city, state, country
